import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import Container from "@/components/shared/Container";
import ReduxProvider from "@/components/ReduxProvider";
import "./globals.css";
import { Toaster } from "sonner";
import AuthProvider from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <Header />
            <Container>
              <Toaster />
              {children}
            </Container>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
